name: Deploy To DigitalOcean

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/README.md'
      - '**/main.yml'
      - '**/release.yml'
      - '**/.gitignore'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key and rsync over SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy to DO
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan $SERVER_IP >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          rsync -r * root@$SERVER_IP:/var/www/html/wp-content/themes/rd
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
